import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Geist } from "next/font/google";
import "./globals.css";
import SidebarSection from "@/shared/components/layouts/SidebarSection";
import { SidebarProvider } from "@/shared/context/sidebar-context";
import MainContent from "@/shared/components/layouts/main-content";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("light", "h-full", "antialiased", plusJakartaSans.variable, "font-sans", geist.variable)}
      style={{ colorScheme: "light" }}
    >
      <body className="min-h-full flex flex-row bg-gray-100 text-gray-900">
        <SidebarProvider>
          <SidebarSection />
          <MainContent>{children}</MainContent>
        </SidebarProvider>
      </body>
    </html>
  );
}
